services:
  auth.webapi:
    image: auth.webapi
    build:
      context: .
      dockerfile: Auth.WebApi/Dockerfile

  customer.webapi:
    image: customer.webapi
    build:
      context: .
      dockerfile: Customer.WebApi/Dockerfile
