services:
  auth.webapi:
    image: auth.webapi
    build:
      context: .
      dockerfile: Auth.WebApi/Dockerfile

  customer.webapi:
    image: customer.webapi
    build:
      context: .
      dockerfile: Customer.WebApi/Dockerfile

  inventory.webapi:
    image: inventory.webapi
    build:
      context: .
      dockerfile: Inventory.WebApi/Dockerfile

  eventsourcing.worker:
    image: eventsourcing.worker
    build:
      context: .
      dockerfile: Workers/EventSourcing.Worker/Dockerfile
